language: python
python:
    - "2.7"
install:
    - python setup.py install
before_script:
    - pip install pytest
script: py.test
deploy:
    provider: pypi
    user: rejown
    password:
        secure: "K6eW3+2aB0vc5BRFw9NmrN7jqTdFID5/AsmXlOfPDfFtdkoRKH4bFZxW22qXQ40Kn5qygWOUlymh1Z1/kb0W0HVInjOIz7NekSyjHlIMLAa9S/bj0ydOoh6wLBBD5SQbtnO7yC2ARtnQ1OEPR2IosqYYNfhXRvnyp0GLHRb14KYQmCnwvAW7JzWPPs8jniJHqir78XmpwhvxD2u3ObjtTpFey6lRzQ1EaWdGWumJmlwooDI+rbJ5DSs/+sPK239ujLHZsiIPZOivlVdwL1S/wErV0TFOZcCNTNJ04dquC7tns8MqxDCz6Rb/9TG4TgevpShp8jTXIaV89dPptDKX3aa9zMXpBf09jiAagjwnvBwbUaNqdUsRCzgw4MFKRzWv1JTqSuHdPM1cU4BRRIVgOvPoLknZJo/thhdtw0Torff63RjVRWAt9bwx0VpMGiovI3ny6cXKSqMmthWOjAWdxcmp0dAXcBH5TP7+LaxDPoPBYwhU2Hd2DP6AZ39yZ9WzApaOvtbIy6wBqvaCDY/sdi6nKjQwMvy/TamKR96/w1BAX6YME3IjKjmZRsiQlEFZckxWQjIqj+/odTHhiqwt3a/7jko5gPVGjPUTA1V2x9W7MEgFyW90JuYud/2BlkKgVyQKjBwRaa99cMLQtmpEmctv1LD/KI0KAKrp3Eql2Xo="
on:
    pythoni: 2.7
    tags: true
    branch: master
